version: 0.0.{build}

skip_branch_with_pr: true

max_jobs: 1
configuration: Release

image: Visual Studio 2022

init:
  - git config --global core.autocrlf input

dotnet_csproj:
  patch: true
  file: '**\*.csproj'

before_build:
  - cd project
  - nuget restore

build:
  parallel: true
  project: project/Snapper.sln
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true

test: off

test_script:
  - ps: dotnet test --no-build

deploy:
  - provider: NuGet
    api_key:
      secure: 2LzZQpLIpwbjbPbBHIu99KyDCChR1uxCmJTUU8/y/5jF1sXKGigu4F86VhoQXinU
    skip_symbols: false
    artifact: /.*\.s?nupkg/
    on:
      appveyor_repo_tag: true

skip_commits:
  files:
    - .all-contributorsrc
    - .editorconfig
    - .gitattributes
    - .gitignore
    - LICENSE
    - README.md
    - SECURITY.md
